# Exploratory Data Analysis

## Project

LLM-Assisted Explainable Misbehavior Reporting Framework for Cooperative Intelligent Transportation Systems

## Objective

Explore the VeReMi dataset to understand feature distributions, class balance, feature relationships, and prepare for preprocessing and machine learning.

In [2]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from pathlib import Path

plt.style.use("ggplot")
sns.set_theme()

DATA_PATH = Path("../data/samples/veremi_sample_100k.csv")

In [3]:
df = pd.read_csv(DATA_PATH)

print(df.shape)

(100000, 21)

In [4]:
df.head()

,Unnamed: 0,type,rcvTime,pos_0,pos_1,pos_noise_0,pos_noise_1,spd_0,spd_1,spd_noise_0,...,acl_0,acl_1,acl_noise_0,acl_noise_1,hed_0,hed_1,hed_noise_0,hed_noise_1,attack,attack_type
0,0,3,27371.216284,981.098535,908.497891,3.826423,3.964059,-17.723786,-2.154895,-0.024182,...,-0.248402,-0.177659,0.000784,1.114785e-03,-0.971331,-0.237732,44.022409,33.840519,0,RandomSpeedOffset
1,1,3,52060.561117,1213.025174,984.277524,4.477449,4.459375,14.504808,2.605276,-0.008523,...,-0.653850,-0.117125,0.000001,1.847528e-07,0.992578,0.121610,2.560114,8.414909,0,DataReplay
2,2,3,28156.319142,140.514133,944.338854,2.965184,3.066191,-0.346027,4.671520,-0.000469,...,0.333247,-4.486889,0.000448,6.050771e-03,0.256103,0.966649,15.915074,9.636057,1,DoSDisruptive
3,3,3,28671.375689,558.005547,327.316562,4.934159,5.037039,11.792797,4.028876,0.022346,...,-0.030639,-0.010265,0.000066,2.237617e-05,0.954113,0.299446,2.854203,6.203941,1,RandomSpeedOffset
4,4,2,53612.000000,689.179631,547.143780,3.327547,3.374621,3.887137,-8.732709,0.000090,...,-1.829939,4.111129,0.000028,6.361425e-05,0.360402,-0.932797,5.648109,19.951521,0,DoS

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 21 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Unnamed: 0   100000 non-null  int64
 1   type         100000 non-null  int64
 2   rcvTime      100000 non-null  float64
 3   pos_0        100000 non-null  float64
 4   pos_1        100000 non-null  float64
 5   pos_noise_0  100000 non-null  float64
 6   pos_noise_1  100000 non-null  float64
 7   spd_0        100000 non-null  float64
 8   spd_1        100000 non-null  float64
 9   spd_noise_0  100000 non-null  float64
 10  spd_noise_1  100000 non-null  float64
 11  acl_0        100000 non-null  float64
 12  acl_1        100000 non-null  float64
 13  acl_noise_0  100000 non-null  float64
 14  acl_noise_1  100000 non-null  float64
 15  hed_0        100000 non-null  float64
 16  hed_1        100000 non-null  float64
 17  hed_noise_0  100000 non-null  float64
 18  hed_noise_1  100000 non-null  float64
 19  attack       100000 non-null  int64
 20  attack_type  100000 non-null  str
dtypes: float64(17), int64(3), str(1)
memory usage: 17.2 MB

In [6]:
df.describe()

,Unnamed: 0,type,rcvTime,pos_0,pos_1,pos_noise_0,pos_noise_1,spd_0,spd_1,spd_noise_0,spd_noise_1,acl_0,acl_1,acl_noise_0,acl_noise_1,hed_0,hed_1,hed_noise_0,hed_noise_1,attack
count,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,49999.500000,2.86317,38627.143428,533.907898,661.373431,4.021270,4.021762,1.177759,1.807361,-0.000001,-0.000008,0.042939,0.033311,0.000797,0.000984,-0.069102,0.031846,13.552928,13.305956,0.454710
std,28867.657797,0.34367,12435.467558,411.777816,317.555422,5.299658,5.299129,9.355129,9.788023,0.011593,0.012684,0.942819,1.190766,0.002446,0.002560,0.642759,0.746604,18.386315,18.728038,0.497947
min,0.000000,2.00000,25207.000000,-1859.393275,-1515.626154,0.000000,0.000000,-25.748742,-24.865998,-0.082744,-0.086862,-4.499567,-4.499789,0.000000,0.000000,-1.000000,-1.000000,0.000000,0.000000,0.000000
25%,24999.750000,3.00000,27175.056646,195.570038,387.769385,3.488613,3.490026,-2.381601,-3.967096,-0.002377,-0.004024,-0.161666,-0.202027,0.000005,0.000005,-0.669503,-0.773359,3.945700,3.555630,0.000000
50%,49999.500000,3.00000,28610.718864,276.310189,719.316302,3.990100,3.989469,0.000076,0.000337,0.000000,0.000000,0.000075,0.000107,0.000065,0.000066,-0.024397,0.052985,9.346724,8.281785,0.000000
75%,74999.250000,3.00000,51937.419094,902.216151,906.251098,4.490791,4.491642,4.495088,7.764322,0.002448,0.003948,0.220860,0.303303,0.000460,0.000751,0.209544,0.839482,17.443448,17.166257,1.000000
max,99999.000000,3.00000,54184.000000,2681.471465,2368.346332,1438.902073,1438.743799,39.997550,39.979137,0.088609,0.087755,4.500752,4.499895,0.067711,0.070758,1.000000,1.000000,3460.534621,3425.047026,1.000000

In [7]:
df.isnull().sum()

Unnamed: 0     0
type           0
rcvTime        0
pos_0          0
pos_1          0
pos_noise_0    0
pos_noise_1    0
spd_0          0
spd_1          0
spd_noise_0    0
spd_noise_1    0
acl_0          0
acl_1          0
acl_noise_0    0
acl_noise_1    0
hed_0          0
hed_1          0
hed_noise_0    0
hed_noise_1    0
attack         0
attack_type    0
dtype: int64

In [8]:
print(df.duplicated().sum())

0